apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-service.fullname" . }}
  labels:
    {{- include "kafka-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.brokerPort }}
      targetPort: broker
      protocol: TCP
      name: broker
    - port: {{ .Values.service.controllerPort }}
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    {{- include "kafka-service.selectorLabels" . | nindent 4 }}
