apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-secret-store
  namespace: my-app
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"
      path: "apps"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: default
          key: token 

