{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "task-service.secretName" . }}

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}

  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}

  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}