apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-service.secretName" . }}
type: Opaque

stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  JWT_EXPIRES_IN: {{ .Values.secrets.JWT_EXPIRES_IN | quote }}
  GATEWAY_SECRET: {{ .Values.secrets.GATEWAY_SECRET | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  AWS_ENDPOINT_URL_S3: {{ .Values.secrets.AWS_ENDPOINT_URL_S3 | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_REGION: {{ .Values.secrets.AWS_REGION | quote }}
  STORAGE_BUCKET: {{ .Values.secrets.STORAGE_BUCKET | quote }}
  KAFKA_BROKERS: {{ .Values.secrets.KAFKA_BROKERS | quote }}