apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.secretName" . }}
type: Opaque

stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  JWT_EXPIRES_IN: {{ .Values.secrets.JWT_EXPIRES_IN | quote }}
  GATEWAY_SECRET: {{ .Values.secrets.GATEWAY_SECRET | quote }}