name: API Gatway Service CI

on:
  push:
    branches:
      - main
    paths:
      - "apps/api-gateway/**"
      - "packages/**"
      - "Dockerfile"
      - "package.json"
      - "package-lock.json"
    
  pull_request:
    paths:
      - "apps/api-gateway/**"
      - "packages/**"
      - "Dockerfile"
      - "package.json"
      - "package-lock.json"
    
jobs:
  media-service:
    uses: ./.github/workflows/reusable-service-ci.yml

    with:
      service: api-gateway
      image_tag: ${{ github.sha }}

    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}